name: nikeappdemo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  firebase_auth: ^6.5.4
  firebase_core: ^4.11.0
  cloud_firestore: ^6.7.1
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.5
  flutter_slidable: ^3.1.0
  flutter_avif: ^3.1.0
  intl: ^0.19.0 # <-- Mình đã thêm intl vào đây

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Khai báo toàn bộ cấu trúc thư mục ảnh
  assets:
    - assets/
    - assets/section1/
    
    # Thư mục Kid
    - assets/kid/bag/
    - assets/kid/hoodies_pullovers/
    - assets/kid/pants_tights/
    - assets/kid/tops_tshirts/
    
    # Thư mục Men
    - assets/men/hoodies_pullovers/
    - assets/men/jackets/
    - assets/men/shorts/
    - assets/men/socks/
    - assets/men/tops_tshirts/
    
    # Thư mục Women
    - assets/women/hoodies_pullovers/
    - assets/women/jackets/
    - assets/women/shorts/
    - assets/women/socks/
    - assets/women/tops_tshirts/