// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDGzhWIWaWGQ_f9OhgSvDNHLeImlsCTr4',
    appId: '1:205047295977:web:a349cdadbb384fa0b32578',
    messagingSenderId: '205047295977',
    projectId: 'nike-01',
    authDomain: 'nike-01.firebaseapp.com',
    storageBucket: 'nike-01.firebasestorage.app',
    measurementId: 'G-QGSX1ZHNNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqHSPbniZAUIzJ29V9FZlSrCI9UAQcr1c',
    appId: '1:205047295977:android:6c65d33e51b53073b32578',
    messagingSenderId: '205047295977',
    projectId: 'nike-01',
    storageBucket: 'nike-01.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHhcZ2Bwm9XfaplAuU92MsJosVUVVMnwA',
    appId: '1:205047295977:ios:cea5ca1cb8d0f60bb32578',
    messagingSenderId: '205047295977',
    projectId: 'nike-01',
    storageBucket: 'nike-01.firebasestorage.app',
    iosBundleId: 'com.example.nikeappdemo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHhcZ2Bwm9XfaplAuU92MsJosVUVVMnwA',
    appId: '1:205047295977:ios:cea5ca1cb8d0f60bb32578',
    messagingSenderId: '205047295977',
    projectId: 'nike-01',
    storageBucket: 'nike-01.firebasestorage.app',
    iosBundleId: 'com.example.nikeappdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDGzhWIWaWGQ_f9OhgSvDNHLeImlsCTr4',
    appId: '1:205047295977:web:50360bb10a2e2db4b32578',
    messagingSenderId: '205047295977',
    projectId: 'nike-01',
    authDomain: 'nike-01.firebaseapp.com',
    storageBucket: 'nike-01.firebasestorage.app',
    measurementId: 'G-1610112DSL',
  );
}
